### ISSUE TITLE
Spec discussion for v2.0.0

### ISSUE THREAD

**Issue by Kuniwak** [jsdoctypeparser/jsdoctypeparser#24]
### New specs
- New AST (see [schemas](https://github.com/Kuniwak/jsdoctypeparser/tree/master/schemas))
- [x] Add `parse` function
- [x] Add `publish` function
- [x] Add `traverse` function
- [x] Support `@type {my-type}` (#15)
- [x] Support `@type {external:String#rot13}` (#11)
- [x] Support `@type {String[]/Number[]}` (#16)
- [x] Support `@type {"string"}`, `@type {123}` (#16)

**Comment by zxqfox** [comment]
Yummy! Can't wait to get it all ;-)

**Comment by Kuniwak** [comment]
I published [v2.0.0-alpha](https://www.npmjs.com/package/jsdoctypeparser).

**Comment by Kuniwak** [comment]
Now, we can see new AST by [online demo](http://kuniwak.github.io/jsdoctypeparser/).

**Comment by Kuniwak** [comment]
I'm gonna seal the spec and close this issue on Aug. 31.
Please comment if you have a spec proposal.

**Comment by Kuniwak** [comment]
In current implementation, AST nodes can have the field `meta.syntax`.
But I think the alter field `meta.style` is probably more useful.
For example, a generic type such as `String[]` have the following field:

```
{
  type: 'GENERIC',
  ...,
  styles: {
    legacyClosureCompiler: false,
    closureCompiler: false,
    jsdoc: true,
    jsduck: true
  }
}
```

@zxqfox What do you think about it?

**Comment by zxqfox** [comment]
Yeah, I think it'd be very helpful for linters. :+1: at my POV.

Just, dunno, scared about performance a bit.

**Comment by Kuniwak** [comment]
> Just, dunno, scared about performance a bit.
Yes, it requires more memory (but amount of time won't change).

OK, I approve the spec on v2.0.0.

**Comment by brettz9** [comment]
The issues listed here appear to be completed, so closing. 

I'm admittedly not clear though on the status of `styles` vs. `syntax`, so feel free to reopen, comment, or file new issues as needed.
